### ISSUE TITLE
About the script's file name. Why don't name it `minAjax.js` rather than with `index.js` ?

### ISSUE THREAD

**Issue by mc-zone** [argunner/minAjax.js#5]
Looks like it should be a single file of script.
Just a discussion. I think maybe `index.js` is not a __typical__ name.
What's your opinion? @argunner

**Comment by argunner** [comment]
:+1:  yeah ! i guess you are right, i never bothered about it but i think i should change it to minAjax.js

**Comment by kevinisaac** [comment]
I guess the issue can be closed.
